export default [
    { key: 'left', label: 'x' }, 
    { key: 'top', label: 'y' }, 
    { key: 'width', label: 'Width' }, 
    { key: 'height', label: 'Height' }, 
    { key: 'color', label: 'Color' }, 
    { key: 'backgroundColor', label: 'Backgroud color' }, 
    { key: 'borderWidth', label: 'Border Width' },
    { key: 'borderStyle', label: 'Border Style' }, 
    { key: 'borderColor', label: 'Border Color' }, 
    { key: 'borderRadius', label: 'Border Radius' }, 
    { key: 'fontSize', label: 'Font size' }, 
    { key: 'fontWeight', label: 'Font weight' }, 
    { key: 'lineHeight', label: 'Line height' }, 
    { key: 'letterSpacing', label: 'Letter Spacing' }, 
    { key: 'textAlign', label: 'Text Align' }, 
    { key: 'verticalAlign', label: 'Vertical Align' },
    { key: 'opacity', label: 'Opacity' }, 
    { key: 'action', label: 'Action' },
    { key: 'dataSource', label: 'Data source' },
]